### ISSUE TITLE
Add ability to include dataset details in API scripts

### ISSUE THREAD

**Issue by empavia** [natcap/data.naturalcapitalproject.stanford.edu#22]
We will need the ability to extract the following information from the MCF and import it into CKAN through the API script:
-Description (required)
-Tags (required)
-License (required)
-Author or maintainer
-Author or maintainer contact information

**Comment by phargogh** [comment]
CKAN's `package_create` function distinguishes between an author and a maintainer, but this distinction doesn't appear in the MCF file format unless we create distinct categories for them under the `contact` heading such as:

```yaml
contact:
    author:
        ....
    maintainer:
        ....
```

For the moment, I'll just take the first section and use that for the contact info.

**Comment by phargogh** [comment]
@empavia as of commit e50844b8309df28b2d10b6519cf2d3cd4bbf5c73 I've added everything in your list except for licensing.

CKAN has its own internal idea of what licenses are valid, and so I need to do a couple things in order to 1) expand the number of licenses CKAN understands and then 2) in the API script, map what's in the MCF to the known license ID.  As a result, the licensing part of your requested list is not yet there, except as in the MCF upload.

**Comment by phargogh** [comment]
@empavia as of commit 4dfa186 (just pushed), all of the dataset details listed have been added to the API script.

Additionally, the script will now _update_ a dataset if it already exists on the catalog, with the `metadata.identifier` being the key thing that identifies the dataset.

**Comment by phargogh** [comment]
Confirmed that Emily can use the script and the mentioned attributes are working.
